from pathlib import Path

from stackops.scripts.python.ai.scripts import (
	DASHBOARD_PATH_REFERENCE,
	LINT_AND_TYPE_CHECK_PATH_REFERENCE,
	MODEL_PATH_REFERENCE,
)

TYPE_CHECKING_SCRIPTS_DIRECTORY = Path("scripts").joinpath("type_checking")
TYPE_CHECKING_SCRIPT_PATH_REFERENCES: tuple[str, ...] = (
	LINT_AND_TYPE_CHECK_PATH_REFERENCE,
	MODEL_PATH_REFERENCE,
	DASHBOARD_PATH_REFERENCE,
)
LINT_AND_TYPE_CHECK_REPO_RELATIVE_PATH = TYPE_CHECKING_SCRIPTS_DIRECTORY.joinpath(
	LINT_AND_TYPE_CHECK_PATH_REFERENCE
)