set -g status-position bottom

set -g status-style "fg=#8a8a8a,bg=#080808"
set -g message-style "fg=#080808,bg=#ffff00,bold"
set -g message-command-style "fg=#ffff00,bg=#080808,bold"
set -g mode-style "fg=#080808,bg=#ffff00,bold"

set -g pane-border-style "fg=#303030"
set -g pane-active-border-style "fg=#00afff"

set -g window-status-style "fg=#8a8a8a,bg=#080808"
set -g window-status-current-style "fg=#080808,bg=#00afff,bold"
set -g window-status-activity-style "fg=default,bg=default,underscore"
set -g window-status-bell-style "fg=#ffff00,bg=default,blink,bold"
set -g window-status-last-style "fg=#00afff,bg=#303030"

set -g window-status-format "#[fg=#8a8a8a,bg=#080808] #I #W#{?#{||:#{window_bell_flag},#{window_zoomed_flag}}, ,}#{?window_bell_flag,!,}#{?window_zoomed_flag,Z,} "
set -g window-status-current-format "#[fg=#080808,bg=#00afff,bold] #I #W#{?#{||:#{window_bell_flag},#{window_zoomed_flag}}, ,}#{?window_bell_flag,!,}#{?window_zoomed_flag,Z,} "

set -g status-left-length 120
set -g status-right-length 120

set -g status-left "#[fg=#080808,bg=#ffff00,bold] ❐ #S #[fg=#e4e4e4,bg=#ff00af] #{b:pane_current_path} #[fg=#080808,bg=#5fff00] #{pane_current_command} "
set -g status-right "#[fg=#8a8a8a,bg=#080808] #{?client_prefix,⌨ ,}#{?#{>:#{session_attached},1},⚇ ,}#{?pane_synchronized,⚏ ,}#{?window_zoomed_flag,Z ,}#{?pane_in_mode,COPY ,}#[fg=#e4e4e4,bg=#d70000] #{?@battery_display,#{@battery_display},AC} #[fg=#080808,bg=#e4e4e4,bold] %H:%M %d %b | #H "
