from typing import Final


HERDR_VERSION: Final[str] = "0.7.3"
HERDR_PROTOCOL: Final[int] = 16
HERDR_COMMAND_TIMEOUT_SECONDS: Final[int] = 15
DEFAULT_RETAIN_PREVIOUS_ITERATIONS: Final[int] = 3
CLOSE_LOOP_INTERVAL_SECONDS: Final[int] = 300
