from typing import Final


DEFAULT_TRACK_MAX_ITERATIONS: Final[int] = 100
TRACK_INTERVAL_SECONDS: Final[int] = 60
DEFAULT_RETAIN_PREVIOUS_ITERATIONS: Final[int] = 3
CLOSE_LOOP_INTERVAL_SECONDS: Final[int] = 300
