MAPPER_DATA_SCHEMA_PATH_REFERENCE = "data.schema.json"
MAPPER_DATA_PATH_REFERENCE = "data.yaml"
MAPPER_DOTFILES_SCHEMA_PATH_REFERENCE = "dotfiles.schema.json"
MAPPER_DOTFILES_PATH_REFERENCE = "dotfiles.yaml"
