from pathlib import Path

DASHBOARD_STATE_DIR = Path.home() / ".cache" / "stackops" / "dashboards"
STARTUP_TIMEOUT_SECONDS = 45.0
HEALTH_TIMEOUT_SECONDS = 1.0
POLL_INTERVAL_SECONDS = 0.1
STOP_TIMEOUT_SECONDS = 5.0
PGWEB_PORT = 42000
STREAMLIT_PORT = 8501
