
from typing import Literal, TypeAlias

BACKENDS: TypeAlias = Literal[
    "marimo",
    "jupyter",
    "jupyter-ai",
    "vscode",
    "visidata",
    "preview",
    "auto",
    "browser",
    "glow",
    "rainfrog",
    "lazysql",
    "dblab",
    "usql",
    "harlequin",
    "sqlit",
    "python",
    "ipython",
]
BACKENDS_LOOSE: TypeAlias = Literal[
    "auto",
    "marimo",
    "m",
    "jupyter",
    "j",
    "jupyter-ai",
    "ja",
    "vscode",
    "c",
    "visidata",
    "v",
    "preview",
    "browser",
    "b",
    "glow",
    "g",
    "rainfrog",
    "r",
    "lazysql",
    "l",
    "dblab",
    "d",
    "usql",
    "u",
    "harlequin",
    "h",
    "sqlit",
    "s",
    "python",
    "p",
    "ipython",
    "i",
]
BACKENDS_MAP: dict[BACKENDS_LOOSE, BACKENDS] = {
    "auto": "auto",
    "marimo": "marimo",
    "m": "marimo",
    "jupyter": "jupyter",
    "j": "jupyter",
    "jupyter-ai": "jupyter-ai",
    "ja": "jupyter-ai",
    "vscode": "vscode",
    "c": "vscode",
    "visidata": "visidata",
    "v": "visidata",
    "preview": "preview",
    "browser": "browser",
    "b": "browser",
    "glow": "glow",
    "g": "glow",
    "rainfrog": "rainfrog",
    "r": "rainfrog",
    "lazysql": "lazysql",
    "l": "lazysql",
    "dblab": "dblab",
    "d": "dblab",
    "usql": "usql",
    "u": "usql",
    "harlequin": "harlequin",
    "h": "harlequin",
    "sqlit": "sqlit",
    "s": "sqlit",
    "python": "python",
    "p": "python",
    "ipython": "ipython",
    "i": "ipython",
}
